### PR TITLE
add a custom fact which shows certificate extensions

### PR DESCRIPTION
**Pull request by tuxmea**
we strip pp_preshared_key

### CODE REVIEW

**Review by alvagante — CHANGES_REQUESTED** [review]
This is what happens once added, to a plain pe client:
        
        Info: Loading facts
        Error: Facter: Error loading fact /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb: /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: syntax error, unexpected '{', expecting `then' or ',' or ';' or '\n'
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\....
                     ^
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                         ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                            ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                               ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                  ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                     ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...hen $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                         ^~~~~~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ... $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:28: syntax error, unexpected `when', expecting `end'
              when $r{^pp_}
              ^~~~
        
        Error: Facter: Error loading fact /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb: /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: syntax error, unexpected '{', expecting `then' or ',' or ';' or '\n'
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\....
                     ^
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                         ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                            ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                               ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                  ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                     ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...hen $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                         ^~~~~~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ... $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:28: syntax error, unexpected `when', expecting `end'
              when $r{^pp_}
              ^~~~
        
        Error: Facter: Error loading fact /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb: /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: syntax error, unexpected '{', expecting `then' or ',' or ';' or '\n'
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\....
                     ^
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                         ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                            ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                               ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                  ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                     ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...hen $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                         ^~~~~~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ... $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:28: syntax error, unexpected `when', expecting `end'
              when $r{^pp_}
              ^~~~
        
        Error: Facter: Error loading fact /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb: /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: syntax error, unexpected '{', expecting `then' or ',' or ';' or '\n'
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\....
                     ^
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                         ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                            ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                               ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                  ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                     ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...hen $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                         ^~~~~~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ... $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:28: syntax error, unexpected `when', expecting `end'
              when $r{^pp_}
              ^~~~
        
        Error: Facter: Error loading fact /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb: /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: syntax error, unexpected '{', expecting `then' or ',' or ';' or '\n'
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\....
                     ^
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                         ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                            ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                               ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                  ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
              when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
                                     ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...hen $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                         ^~~~~~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ... $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
        ...{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
        ...                             ^~
        /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:28: syntax error, unexpected `when', expecting `end'
              when $r{^pp_}
              ^~~~

**Comment by alvagante** [comment]
What's the purpose of such a fact when there's already the internal $trusted variable? https://puppet.com/docs/puppet/5.5/lang_facts_and_builtin_vars.html#trusted-facts

**Comment by tuxmea** [comment]
> This is what happens once added, to a plain pe client:
> 
> ```
>     Info: Loading facts
>     Error: Facter: Error loading fact /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb: /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: syntax error, unexpected '{', expecting `then' or ',' or ';' or '\n'
>           when $r{^1\.3\.6\.1\.4\.1\.34380\.1\....
>                  ^
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>           when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>                      ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>           when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>                         ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>           when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>                            ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>           when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>                               ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>           when $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>                                  ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>     ...hen $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>     ...                         ^~~~~~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>     ... $r{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>     ...                             ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:24: no .<digit> floating literal anymore; put 0 before dot
>     ...{^1\.3\.6\.1\.4\.1\.34380\.1\.1}
>     ...                             ^~
>     /opt/puppetlabs/puppet/cache/lib/facter/cert_extension_fact.rb:28: syntax error, unexpected `when', expecting `end'
>           when $r{^pp_}
>           ^~~~
>     


fixed

$trusted is not a fact but a server variable!
Using this fact allows people to get the cert extensions on the agent and it simplifies testing especially when setting variables based on $trusted.

**Comment by alvagante** [comment]
I know it's not a fact, but it still available at compile time, and on the client the cert extensions are the ones you expect to see in csr_attributes.yaml file. Honesty I don't think a fact for such a specific use case should stay here.

**Comment by tuxmea** [comment]
do whatever you like.

**Pull request closed without merging**
